/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainmenu;

import Game.Celebrity;
import javafx.scene.paint.Color;
import sounds.Player;

/**
 *
 * @author NightOmicron
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    static Player menutheme = new Player();
    public MainMenu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Celebrity = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Celebrity.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        Celebrity.setForeground(new java.awt.Color(255, 255, 255));
        Celebrity.setText("Demo Version");
        Celebrity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CelebrityMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CelebrityMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CelebrityMouseExited(evt);
            }
        });
        getContentPane().add(Celebrity, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 230, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainmenu/MenuScreenRes.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CelebrityMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CelebrityMouseEntered
        Celebrity.setForeground(new java.awt.Color(255, 102, 0));
    }//GEN-LAST:event_CelebrityMouseEntered

    private void CelebrityMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CelebrityMouseExited
        Celebrity.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_CelebrityMouseExited

    private void CelebrityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CelebrityMouseClicked
        new Celebrity().setVisible(true);
        menutheme.stopSound();
        this.dispose();
    }//GEN-LAST:event_CelebrityMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
                String filepath = "src/sounds/Opening.wav";
                
                menutheme.setFile(filepath);
                menutheme.playSound();
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Celebrity;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
